from github import Github
import time
from config import GITHUB_TOKEN, GITHUB_OWNER, GITHUB_REPO

g = Github(GITHUB_TOKEN)
repo = g.get_repo(f"{GITHUB_OWNER}/{GITHUB_REPO}")


def get_open_issues():
    """Fetch all open issues from the repository."""
    issues = repo.get_issues(state="open")
    result = []
    for issue in issues:
        # Skip pull requests (GitHub API returns PRs as issues too)
        if issue.pull_request is None:
            result.append({
                "number": issue.number,
                "title": issue.title,
                "body": issue.body or "",
                "labels": [l.name for l in issue.labels],
            })
    return result


def get_repo_files(path="", extensions=None):
    """Recursively list all files in the repository."""
    if extensions is None:
        extensions = [
            ".py", ".js", ".ts", ".jsx", ".tsx", ".java", ".go", ".rs", ".rb", ".php",
            ".c", ".cpp", ".h", ".cs", ".html", ".css", ".json", ".xml", ".sql",
            ".md", ".txt", ".yml", ".yaml", ".toml", ".cfg", ".ini",
            ".sh", ".bat", ".dockerfile",
        ]

    files = []
    try:
        contents = repo.get_contents(path, ref="main")
    except Exception:
        contents = repo.get_contents(path)

    while contents:
        file_content = contents.pop(0)
        if file_content.type == "dir":
            try:
                contents.extend(repo.get_contents(file_content.path, ref="main"))
            except Exception:
                contents.extend(repo.get_contents(file_content.path))
        else:
            if any(file_content.path.endswith(ext) for ext in extensions):
                files.append(file_content.path)
    return files


def get_file_content(file_path):
    """Fetch the content of a specific file from the repo."""
    try:
        contents = repo.get_contents(file_path, ref="main")
    except Exception:
        contents = repo.get_contents(file_path)
    return contents.decoded_content.decode("utf-8")


def create_pull_request(file_path, new_code, issue_title, issue_number=None):
    """Create a branch, update the file, and open a pull request."""
    branch_name = f"ai-fix-{int(time.time())}"

    # Get the default branch SHA
    try:
        source = repo.get_branch("main")
    except Exception:
        source = repo.get_branch(repo.default_branch)

    # Create a new branch
    repo.create_git_ref(
        ref=f"refs/heads/{branch_name}",
        sha=source.commit.sha
    )

    # Get the current file to obtain its SHA
    try:
        contents = repo.get_contents(file_path, ref="main")
    except Exception:
        contents = repo.get_contents(file_path)

    # Update the file on the new branch
    repo.update_file(
        contents.path,
        f"AI Fix: {issue_title}",
        new_code,
        contents.sha,
        branch=branch_name
    )

    # Build PR body
    body = "This PR was automatically generated by the AI agent to fix an issue."
    if issue_number:
        body += f"\n\nCloses #{issue_number}"

    # Create the pull request
    pr = repo.create_pull(
        title=f"AI Fix: {issue_title}",
        body=body,
        head=branch_name,
        base="main"
    )

    return pr.html_url

def get_repo_info():
    """Get basic repository information."""
    return {
        "name": repo.name,
        "full_name": repo.full_name,
        "description": repo.description,
        "owner_avatar": repo.owner.avatar_url,
        "stars": repo.stargazers_count,
        "forks": repo.forks_count
    }

def get_pull_requests():
    """Fetch all open pull requests from the repository."""
    prs = repo.get_pulls(state="open")
    result = []
    for pr in prs:
        result.append({
            "number": pr.number,
            "title": pr.title,
            "body": pr.body or "",
            "url": pr.html_url,
            "state": pr.state,
            "user": pr.user.login,
            "created_at": pr.created_at.isoformat()
        })
    return result

def create_issue(title, body):
    """Create a new issue in the repository."""
    issue = repo.create_issue(title=title, body=body)
    return {
        "number": issue.number,
        "title": issue.title,
        "body": issue.body,
        "url": issue.html_url
    }