"""
repo_manager.py

Git control layer for git_ai.
Handles branch creation, staging, and committing using GitPython.

Branch naming: ai-fix-<component>-<YYMMDD-HHMMSS>
Guarantees uniqueness and is human-readable in git log.
"""

import sys
from datetime import datetime
from pathlib import Path
from dataclasses import dataclass

try:
    import git  # type: ignore  (GitPython)
    GITPYTHON_AVAILABLE = True
except ImportError:
    GITPYTHON_AVAILABLE = False


# ── Data model ────────────────────────────────────────────────────────────────

@dataclass
class CommitResult:
    success: bool
    branch: str = ""
    commit_sha: str = ""
    error: str = ""


# ── Helpers ───────────────────────────────────────────────────────────────────

def _branch_name(component: str) -> str:
    """ai-fix-login-260313-195537 — datestamp keeps names unique."""
    timestamp = datetime.now().strftime("%y%m%d-%H%M%S")
    safe_component = component.replace(" ", "_").lower()[:20]
    return f"ai-fix-{safe_component}-{timestamp}"


def _commit_message(issue: str, component: str) -> str:
    return (
        f"AI Fix: {component} validation bug\n\n"
        f"Issue: {issue}\n"
        f"Generated by git_ai assistant"
    )


# ── Core operations ───────────────────────────────────────────────────────────

def open_repo(repo_path: str) -> "git.Repo":
    """
    Open the git repository at *repo_path* (walks up to find .git if needed).
    Raises git.InvalidGitRepositoryError if none found.
    """
    if not GITPYTHON_AVAILABLE:
        raise ImportError("GitPython is not installed. Run: pip install GitPython")
    return git.Repo(repo_path, search_parent_directories=True)


def create_branch(repo: "git.Repo", branch_name: str) -> "git.Head":
    """
    Create and checkout *branch_name* from the current HEAD.
    If the branch already exists (edge case), delete and recreate it.
    """
    if branch_name in [h.name for h in repo.heads]:
        repo.delete_head(branch_name, force=True)
    new_branch = repo.create_head(branch_name)
    new_branch.checkout()
    return new_branch


def stage_files(repo: "git.Repo", file_paths: list[str]) -> None:
    """
    Stage a list of file paths (relative to the repo root, or absolute).
    Converts absolute paths to relative ones automatically.
    """
    root = Path(repo.working_dir).resolve()
    relative = []
    for fp in file_paths:
        p = Path(fp).resolve()
        try:
            relative.append(str(p.relative_to(root)))
        except ValueError:
            relative.append(fp)          # already relative or out of tree
    repo.index.add(relative)


def commit_changes(
    repo: "git.Repo",
    message: str,
    author_name: str = "git_ai",
    author_email: str = "git_ai@local",
) -> "git.Commit":
    """Commit the currently staged index."""
    from git import Actor  # type: ignore
    author = Actor(author_name, author_email)
    return repo.index.commit(message, author=author, committer=author)


# ── High-level convenience ────────────────────────────────────────────────────

def branch_and_commit(
    repo_path: str,
    modified_files: list[str],
    issue_text: str,
    component: str = "unknown",
) -> CommitResult:
    """
    One-shot workflow:
      1. Open repo
      2. Create new branch
      3. Stage modified files
      4. Commit

    Args:
        repo_path:      Path to the repository root (or any subdirectory).
        modified_files: List of file paths that were changed (relative to repo root).
        issue_text:     The raw issue description (used in commit message).
        component:      Detected component name (used in branch name + commit title).

    Returns:
        CommitResult with branch name and commit SHA on success.
    """
    if not GITPYTHON_AVAILABLE:
        return CommitResult(
            success=False,
            error="GitPython not installed. Run: pip install GitPython",
        )

    try:
        repo   = open_repo(repo_path)
        branch = _branch_name(component)
        create_branch(repo, branch)

        # Stage the target files — works for new (untracked) AND modified files
        abs_paths = [str((Path(repo.working_dir) / f).resolve()) for f in modified_files]
        repo.git.add("--", *abs_paths)

        # Check if anything is actually staged using git status --porcelain
        status_output = repo.git.status("--porcelain")
        has_staged = any(
            line[:2].strip() and not line.startswith("??")
            for line in status_output.splitlines()
            if line
        )

        if not has_staged:
            return CommitResult(success=False, error="Nothing to commit after staging files")

        msg    = _commit_message(issue_text, component)
        commit = commit_changes(repo, msg)

        return CommitResult(
            success=True,
            branch=branch,
            commit_sha=commit.hexsha[:8],
        )

    except Exception as exc:  # noqa: BLE001
        return CommitResult(success=False, error=str(exc))


def print_commit_result(result: CommitResult) -> None:
    if result.success:
        print(f"  ✔ Branch  : {result.branch}")
        print(f"  ✔ Commit  : {result.commit_sha}")
    else:
        print(f"  ✘ Git error: {result.error}", file=sys.stderr)


if __name__ == "__main__":
    # Quick sanity check
    r = branch_and_commit(
        repo_path=".",
        modified_files=["sample_project/login.py"],
        issue_text="Fix login crash when password empty",
        component="login",
    )
    print_commit_result(r)
