import time
from services.db_service import create_pull_request, update_file_content

def create_pr(db, repo_id, issue_title, new_code, file_path, author_id):
    """Update file in DB and create a pull request record."""
    
    # In a real system, we'd branch. Here, we just directly update the DB file for simplicity
    # and create a PR record to show it happened.
    update_file_content(db, repo_id, file_path, new_code)
    
    branch_name = f"ai-fix-{int(time.time())}"
    pr_body = f"This PR was automatically generated by the AI agent to fix an issue.\n\nModified {file_path}"
    
    pr = create_pull_request(
        db, 
        repo_id, 
        title=f"AI Fix: {issue_title}", 
        body=pr_body, 
        branch_name=branch_name,
        author_id=author_id
    )
    
    return f"/repo/{repo_id}/pulls/{pr.id}"