import time
from services.db_service import create_pull_request, update_file_content

def create_pr(db, repo_id, issue_title, original_code, new_code, file_path, author_id, review_text, issue_id=None):
    """Save AI fix proposal into a PR record (does NOT overwrite source files)."""
    
    branch_name = f"ai-fix-{int(time.time())}"
    pr_body = f"This PR was automatically generated by the AI agent to fix an issue.\n\nModified {file_path}\n\nAI Review Summary:\n{review_text}"
    
    pr = create_pull_request(
        db=db, 
        repo_id=repo_id, 
        issue_id=issue_id,
        title=f"AI Fix: {issue_title}", 
        body=pr_body, 
        branch_name=branch_name,
        author_id=author_id,
        target_path=file_path,
        original_code=original_code,
        proposed_code=new_code,
        ai_review=review_text
    )
    
    return f"/repo/{repo_id}/pulls/{pr.id}"